### ISSUE TITLE
Constructor `simpleFigure` for Figure elements

### ISSUE THREAD

**Issue by tarleb** [tarleb/pandoc#9]
Figures are currently represented as `Para`s that contain a single `Image` element. This could be made more consistent by using a `simpleFigure` constructor to create these special elements.

So instead of

``` haskell
B.para $ B.imageWith attr url ("fig:" <> tit) caption
```

we should be able to write something like

``` haskell
B.simpleFigure attr caption url title
```

The builders live in module Text.Pandoc.Builder in the [pandoc-types](https://github.com/jgm/pandoc-types) package.

**Comment by argent0** [comment]
I was thinking about starting with this constructor, and adding it to the `Builder`. This would be the pandoc's equivalent of JATS's [`<graphic>` ](https://jats.nlm.nih.gov/archiving/tag-library/1.1d1/n-xbt0.html) tag
